create table attendances (id uuid not null, status smallint check (status between 0 and 2), lesson_id uuid not null, user_id uuid not null, primary key (id));
create table courses (id uuid not null, level varchar(255), name varchar(255) not null, primary key (id));
create table lessons (id uuid not null, end_time timestamp(6) with time zone not null, start_time timestamp(6) with time zone not null, course_id uuid not null, primary key (id));
create table participants (id uuid not null, course_id uuid not null, user_id uuid not null, primary key (id));
create table user_passes (id uuid not null, created_at timestamp(6), end_time timestamp(6), start_time timestamp(6), user_id uuid not null, primary key (id));
create table user_passes_courses (user_pass_id uuid not null, courses_id uuid not null);
create table users (id uuid not null, created_at timestamp(6), email varchar(255) not null, first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), username varchar(255) not null, primary key (id));
alter table if exists user_passes_courses drop constraint if exists UK2pmjoib75w29i1yo3lth5kb46;
alter table if exists user_passes_courses add constraint UK2pmjoib75w29i1yo3lth5kb46 unique (courses_id);
alter table if exists users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists attendances add constraint FK4s1oy9mebh4q8nog69l2oko8t foreign key (lesson_id) references lessons;
alter table if exists attendances add constraint FK8o39cn3ghqwhccyrrqdesttr8 foreign key (user_id) references users;
alter table if exists lessons add constraint FK17ucc7gjfjddsyi0gvstkqeat foreign key (course_id) references courses;
alter table if exists participants add constraint FK94seswtfpkwlh3efjdso4hlv3 foreign key (course_id) references courses;
alter table if exists participants add constraint FKghixrahoj1s8cloinfx8lyeqa foreign key (user_id) references users;
alter table if exists user_passes add constraint FKhvpdv6o1wkr26yc6k4mdgv3kc foreign key (user_id) references users;
alter table if exists user_passes_courses add constraint FKgtj8j2jpo63x2j7wd3ocj1itb foreign key (courses_id) references courses;
alter table if exists user_passes_courses add constraint FK9jn8scss6q8f9kknb7mx75r9l foreign key (user_pass_id) references user_passes;
